---
title: "Make plots to show fish diversity across the region and the contribution of parks and sites"
author: "MPeipoch"
date: "2023-12-03"
output: pdf_document
---

Necessary packages for the script
```{r, echo=FALSE}
# required packages
req_packs <- c("ggplot2", "dplyr", "vegan", "tidyr","stringr","openxlsx","sf","raster","trend","lubridate","FSA",
               "googleVis","dendextend","ape","cowplot")


########### if installed, then install and load ###################################
new_packs <- req_packs[!(req_packs %in% installed.packages()[,"Package"])]
if (length(new_packs) > 0) {
  install.packages(new_packs,dependencies=T)
}

lapply(req_packs, function(pkg) {
  if (!require(pkg, character.only = TRUE)) {
    stop(paste("Package", pkg, "could not be loaded. Fix it!"))
  }
  library(pkg, character.only = TRUE)
})




```


RICHNESS OF FISH COMMUNITY at the NCRN, PARKS and SITES 
Uses dataset 'all_fish_diversity_data.csv' from FishDataCleaning script 
```{r}

###Import data file 

setwd("/Volumes/Stroud Users/Peipoch/Private/dataAnalysis/R/Rstudio/FishAnalysisNCRN/Datasets/")
fishDataSite = read.csv("all_fish_diversity_data.csv")
fishCountSite = read.csv("all_fish_count_data.csv")
fishDataPark = read.csv("all_fish_diversity_data_byPark.csv")
  
 

ggplot(fishDataSite, aes(x = samplingYear, y = SpeciesRichness, color = site)) +
  geom_point(size = 3) +
  geom_line(aes(group = site), size = 1) +
  facet_wrap(~Park, scales = "free_y", ncol = 2) +
  scale_color_viridis_d() +  # Use viridis color palette
  labs(title = "Fish Diversity Over Time",
       x = "Year",
       y = "Species Richness",
       color = "Site") +
  theme_minimal() +
  theme(legend.position = "right")  # Position the legend to the right


#Four panel plot###########################################################################

# Calculate average Species Richness per Park
average_species_richness <- aggregate(SpeciesRichness ~ Park, data = fishDataSite, FUN = mean)

# Plot 1: Species Richness by Park (Upper Left)
plot1 = ggplot(fishDataSite, aes(x = Park, y = SpeciesRichness, fill = Park)) +
  geom_boxplot() +
  labs(title = "Average Species Richness by Park", x = "Park", y = "Average Species Richness") +
  scale_fill_manual(values = c("#603913","#8DC63F", "#93C2E2","#7851C4", "#2BB673","#F7941E",
                    "#DBCA65","#58595B","#A97C50","#C2B59B",
                    "#000000"))+
  theme(legend.position = "none")

# Plot 2: Barplot of Shannon and Simpson Indices by Park (Upper Right)
plot2 = ggplot(fishDataSite, aes(x = Park, y = SimpsonIndex, fill = Park)) +
  geom_boxplot() +
  labs(title = "Average Species Richness by Park", x = "Park", y = "Average Species Richness") +
  scale_fill_manual(values = c("#603913","#8DC63F", "#93C2E2","#7851C4", "#2BB673","#F7941E",
                    "#DBCA65","#58595B","#A97C50","#C2B59B",
                    "#000000"))+
  theme(legend.position = "none")

# Plot 3: Species Richness by Park and Year (Lower Left)
plot3 = ggplot(fishDataSite, aes(x = factor(samplingYear), y = SpeciesRichness, fill = Park)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), width = 0.7) +
  labs(title = "Species Richness by Park and Year", x = "Year", y = "Species Richness") +
  theme(legend.position = "bottom") +
  scale_fill_manual(values = c("#603913", "#8DC63F", "#93C2E2", "#7851C4", "#2BB673", "#F7941E",
                               "#DBCA65", "#58595B", "#A97C50", "#C2B59B", "#000000"))

# Plot 4: Shannon and Simpson Indices by Site in Parks PRWI and ROCR (Lower Right)
filtered_data = subset(fishDataSite, Park %in% c("PRWI", "ROCR"))
plot4 = ggplot(filtered_data, aes(x = samplingYear, y = ShannonIndex, color = site)) +
  geom_point() +
  geom_line() +
  labs(title = "Shannon Index by Site in Parks PRWI and ROCR", x = "Year", y = "Shannon Index") +
  theme(legend.position = "bottom")

# Combine all plots into a 2x2 grid
final_plot <- plot_grid(plot1, plot2, plot3, plot4, ncol = 2)

# Display the final plot
print(final_plot)

```

DENDOGRAM OF ALL SITES 
Uses dataset 'all_fish_matrix_data.csv' from datasets folder
```{r}



fishCountMatrix = read.csv("all_fish_matrix_data.csv")


fishCountData = fishCountMatrix[, -(1:3)]
row.names(fishCountData) = paste(fishCountMatrix$Park, fishCountMatrix$site, fishCountMatrix$year,sep = "_")

dist_matrix = dist(scale(fishCountData))
hclust_result = hclust(dist_matrix, method = "complete")


plot(as.phylo(hclust_result), type = "fan")

plot(as.phylo(hclust_result), type = "unrooted", cex = 0.6,
     no.margin = TRUE)

# Default plot
plot(as.phylo(hclust_result), cex = 0.6, label.offset = 0.5)




#couldn't figure out how to edit colors and text with dendextend package
dend <- as.dendrogram(hclust_result)



```



