---
title: "NMDS plot and analysis of NCRN fish populations"
author: "MPeipoch"
date: "2023-12-03"
output: pdf_document
---

Necessary packages for the script
```{r, echo=FALSE}
# required packages
req_packs <- c("ggplot2", "dplyr", "vegan", "tidyr","stringr","openxlsx","sf","raster","trend","lubridate","FSA")


########### if installed, then install and load ###################################
new_packs <- req_packs[!(req_packs %in% installed.packages()[,"Package"])]
if (length(new_packs) > 0) {
  install.packages(new_packs,dependencies=T)
}

lapply(req_packs, function(pkg) {
  if (!require(pkg, character.only = TRUE)) {
    stop(paste("Package", pkg, "could not be loaded. Fix it!"))
  }
  library(pkg, character.only = TRUE)
})




```

FISH COMMUNITY COMPOSITON ACROSS SITES
Uses dataset 'all_fish_count_data.csv' from FishDataCleaning script and  the lastest '20231128_wqp_wqx_bss_wq_npsncrn.csv' dataset from Charlie.
```{r}

###Import data file 

setwd("G:/My Drive/NPS_FishDataAnalysis/")
fishData = read.csv("all_fish_count_data.csv")
WatshdData = read.csv("NCRN-Water-Sites-Analysis_2024_01_05.csv")



# Use pivot_wider to transform the data into horizontal format and consolidate with dplyr

horizontal_data <- pivot_wider(fishData, names_from = SubjectTaxonomicName, 
                               values_from = TotalCount)

fishData_horiz = horizontal_data %>%
  group_by(Park,site,samplingYear) %>%
  summarise_all(list(sum = ~sum(., na.rm = TRUE))) %>%
  rename_with(~sub("_sum$", "", .))

# Create a dummy variable based on year difference
fishData_horiz = fishData_horiz %>%
  group_by(site) %>%
  mutate(X = samplingYear - min(samplingYear))

#many species have all zeros (npt even fish), we should remove them prior to running NMDS
column_sums = colSums(fishData_horiz[ ,5:ncol(fishData_horiz)])
lowAbundFish = names(column_sums[column_sums < 20])
not_fish <- c("Eurycea bislineata","Salamander", "Rana clamitans","Desmognathus fuscus","Rana sp.","Faxonius virilis","
Procambarus clarkii","Lithobates sp.","Faxonius limosus","Lithobates catesbeianus","Crayfish")

fishData_horiz = fishData_horiz %>%
  dplyr::select(-one_of(lowAbundFish), 
                -one_of(not_fish))


###################################### NMDS Analysis

fishData_horiz_num = as.data.frame(fishData_horiz[ ,5:ncol(fishData_horiz)])
row.names(fishData_horiz_num) = paste(fishData_horiz$site,fishData_horiz$X, sep="_")

# Running NMDS 
fishData_NMS = metaMDS(fishData_horiz_num,
          distance = "euclidean",
          k = 3,
          maxit = 999, 
          trymax = 500,
          wascores = TRUE)

# Shepards test/goodness of fit
goodness(fishData_NMS) # Produces a results of test statistics for goodness of fit for each point

stressplot(fishData_NMS) # Produces a Shepards diagram


# Extract score values for where sites are located.
data_scores <- as.data.frame(scores(fishData_NMS)$sites)
data_scores$site <- rownames(data_scores) ; rownames(data_scores) = NULL
temp_matrix = str_split_fixed(data_scores$site, '_', 2)
data_scores$site <- temp_matrix[,1]

par(mfrow = c(1,1))
ordiplot(fishData_NMS,type="n")
orditorp(fishData_NMS,display="species",col="red",air=0.01)
orditorp(fishData_NMS,display="sites",cex=1.25,air=0.01)


#plot the scores
data_scores <- as.data.frame(scores(fishData_NMS)$sites)
data_scores$Park <- fishData_horiz$Park
data_scores$year <- fishData_horiz$X

ggplot() +

  geom_point(data = data_scores, aes(x = NMDS1, y = NMDS2, 
                                     color = Park), size = 2.5) +
  scale_colour_manual(values=c("#603913","#8DC63F", "#93C2E2","#7851C4", "#2BB673","#F7941E",
                    "#DBCA65","#58595B","#A97C50","#C2B59B",
                    "#000000")) +
  xlim(-1,0.5) + ylim(-1,1) + theme_classic() 






# Assessing species significance and Extract loading for species/growth forms
fishData_NMS.envfit <- envfit(fishData_NMS, fishData_horiz,permutations=999)

data_loadings = as.data.frame(scores(fishData_NMS.envfit, "vectors"))


```

