---
title: "FishCommunityAnalysis_NPS_2023"
author: "MPeipoch"
date: "2023-12-03"
output: pdf_document
---

Necessary packages for the script
```{r, echo=FALSE}
# required packages
req_packs <- c("ggplot2", "dplyr", "vegan", "tidyr","stringr","openxlsx","sf","raster","trend","lubridate","FSA")


########### if installed, then install and load ###################################
new_packs <- req_packs[!(req_packs %in% installed.packages()[,"Package"])]
if (length(new_packs) > 0) {
  install.packages(new_packs,dependencies=T)
}

lapply(req_packs, function(pkg) {
  if (!require(pkg, character.only = TRUE)) {
    stop(paste("Package", pkg, "could not be loaded. Fix it!"))
  }
  library(pkg, character.only = TRUE)
})




```

FISH COMMUNITY COMPOSITON ACROSS SITES
```{r}

###Import data file 

setwd("G:/My Drive/NPS_FishDataAnalysis/")
fishData = read.csv("all_fish_count_data.csv")
WatshdData = read.csv("NCRN-Water-Sites-Analysis_2024_01_05.csv")



# Use pivot_wider to transform the data into horizontal format and consolidate with dplyr

horizontal_data <- pivot_wider(fishData, names_from = SubjectTaxonomicName, 
                               values_from = TotalCount)

fishData_horiz = horizontal_data %>%
  group_by(Park,site,samplingYear) %>%
  summarise_all(list(sum = ~sum(., na.rm = TRUE))) %>%
  rename_with(~sub("_sum$", "", .))

# Create a dummy variable based on year difference
fishData_horiz = fishData_horiz %>%
  group_by(site) %>%
  mutate(X = samplingYear - min(samplingYear))

#many species have all zeros (npt even fish), we should remove them prior to running NMDS
column_sums = colSums(fishData_horiz[ ,5:ncol(fishData_horiz)])
lowAbundFish = names(column_sums[column_sums < 20])
not_fish <- c("Eurycea bislineata","Salamander", "Rana clamitans","Desmognathus fuscus","Rana sp.","Faxonius virilis","
Procambarus clarkii","Lithobates sp.","Faxonius limosus","Lithobates catesbeianus","Crayfish")

fishData_horiz = fishData_horiz %>%
  dplyr::select(-one_of(lowAbundFish), 
                -one_of(not_fish))


###################################### NMDS Analysis

fishData_horiz_num = as.data.frame(fishData_horiz[ ,5:ncol(fishData_horiz)])
row.names(fishData_horiz_num) = paste(fishData_horiz$site,fishData_horiz$X, sep="_")

# Running NMDS 
fishData_NMS = metaMDS(fishData_horiz_num,
          distance = "euclidean",
          k = 3,
          maxit = 999, 
          trymax = 500,
          wascores = TRUE)

# Shepards test/goodness of fit
goodness(fishData_NMS) # Produces a results of test statistics for goodness of fit for each point

stressplot(fishData_NMS) # Produces a Shepards diagram


# Extract score values for where sites are located.
data_scores <- as.data.frame(scores(fishData_NMS)$sites)
data_scores$site <- rownames(data_scores) ; rownames(data_scores) = NULL
temp_matrix = str_split_fixed(data_scores$site, '_', 2)
data_scores$site <- temp_matrix[,1]

par(mfrow = c(1,1))
ordiplot(fishData_NMS,type="n")
orditorp(fishData_NMS,display="species",col="red",air=0.01)
orditorp(fishData_NMS,display="sites",cex=1.25,air=0.01)


#plot the scores
data_scores <- as.data.frame(scores(fishData_NMS)$sites)
data_scores$Park <- fishData_horiz$Park
data_scores$year <- fishData_horiz$X

ggplot() +

  geom_point(data = data_scores, aes(x = NMDS1, y = NMDS2, 
                                     color = Park), size = 2.5) +
  scale_colour_manual(values=c("#603913","#8DC63F", "#93C2E2","#7851C4", "#2BB673","#F7941E",
                    "#DBCA65","#58595B","#A97C50","#C2B59B",
                    "#000000")) +
  xlim(-1,0.5) + ylim(-1,1) + theme_classic() 






# Assessing species significance and Extract loading for species/growth forms
fishData_NMS.envfit <- envfit(fishData_NMS, fishData_horiz,permutations=999)

data_loadings = as.data.frame(scores(fishData_NMS.envfit, "vectors"))


```

FISH SPECIES TRENDS PER PARK
```{r}

##Import data file 

setwd("G:/My Drive/NPS_FishDataAnalysis/")
fishData = read.csv("all_fish_count_data.csv")

# Create a dummy variable based on year difference
fishData = fishData %>%
  group_by(site) %>%
  mutate(X = samplingYear - min(samplingYear))

#subset each species
fishData_subset = fishData %>%
  filter(., SubjectTaxonomicName == "Cottus spp.")



#plot the data
ggplot(fishData_subset, aes(x = X, y = TotalCount)) +
  geom_line(size = 1) +
  geom_point(size = 3, shape = 16) +  # Use shape 16 for solid dots
  labs(title = "Fish Species Abundance Over Years",
       x = "Year",
       y = "Number of Individuals") +
  theme_minimal() +
  facet_wrap(~site, scales = "free_y")


```

FISH DIVERSITY 
```{r}

###Import data file 

setwd("G:/My Drive/NPS_FishDataAnalysis/")
fishData = read.csv("all_fish_diversity_data.csv")
  


# Create a dummy variable based on year difference
fishData = fishData %>%
  group_by(site) %>%
  mutate(X = samplingYear - min(samplingYear))



#plot the data
ggplot(fishData, aes(x = X, y = SpeciesRichness)) +
  geom_line(size = 1) +
  geom_point(size = 3, shape = 16) +  # Use shape 16 for solid dots
  labs(title = "Species Richness Over Years",
       x = "Year",
       y = "Number of Individuals") +
  theme_minimal() +
  facet_wrap(~site, scales = "free_y")

```









Population estimates for 2-pass removal data. 
```{r}

###Import data file 

setwd("G:/My Drive/NPS_FishDataAnalysis/")
wdata = read.csv("20231128_wqp_wqx_bss_wq_npsncrn.csv")
  

  
###Create a vector with the unique sites in USNPS NCRN Biological stream survey

sites = unique(wdata$MonitoringLocationIdentifier)



###Create dataframes of  in which all population estimations per site and year is stored with a consistent output format in a single file
  
  
  NCRNFishPopEstData = data.frame(matrix(nrow = 0, ncol = 9))
    colnames(NCRNFishPopEstData) = c("Id","No", "No.se", "No.LCI", "No.UCI",
                                  "p", "p.se", "p.LCI", "p.UCI")

      pop_est_results = data.frame(matrix(nrow = 0, ncol = 9))
        colnames(pop_est_results) = c("Id","No", "No.se", "No.LCI", "No.UCI",
                                      "p", "p.se", "p.LCI", "p.UCI")

  
 for (site in sites) {
  
  # Subset data for each site
  temp_data = wdata %>% 
    dplyr::filter(MonitoringLocationIdentifier == site)

    
        temp_data_subset = temp_data %>% #select variable per site and method 
          dplyr::filter(CharacteristicName %in% c("fish - count of individuals captured by species","fish specimens captured electrofishing pass 1","fish specimens captured electrofishing pass 2"))

 out_data = temp_data_subset %>%
  mutate(samplingYear =  as.factor(year(temp_data_subset$ActivityStartDate))) %>%
    group_by(samplingYear, SubjectTaxonomicName, SampleCollectionMethod.MethodDescriptionText) %>%
    summarise(TotalCount = sum(as.numeric(ResultMeasureValue),na.rm=T))
  
 out_data$group = with(out_data,interaction(samplingYear,SubjectTaxonomicName,sep = "_"))
 
 ## split the catch by the different groups (creates a list of catch vectors)
ds = split(out_data$TotalCount,out_data$group)

 #There are many list object with no data or one value, we'll exclude them from further analysis
            for (i in seq_along(ds)) {
              if (length(ds[[i]]) == 2) {
                
               pop_est =  removal(ds[[i]],method="Seber2")
               pop_est = as.data.frame(pop_est$est)
               pop_est = as.data.frame(t(pop_est))
               row.names(pop_est) = paste(site,names(ds)[i], sep="_")
               pop_est <- pop_est %>%
                  tibble::rownames_to_column(var = "Id")
               

               
              } else {next}
                           pop_est_results = rbind(pop_est_results,pop_est)
                           
                           }

NCRNFishPopEstData = rbind(NCRNFishPopEstData,pop_est_results)
pop_est_results = data.frame(matrix(nrow = 0, ncol = 9))
        colnames(pop_est_results) = c("Id","No", "No.se", "No.LCI", "No.UCI",
                                      "p", "p.se", "p.LCI", "p.UCI")
}
  
  
# keep only complete cases and separate Id column into three columns
complete_cases_NCRNFishPopEstData = NCRNFishPopEstData[complete.cases(NCRNFishPopEstData), ]
separated_dataset <- complete_cases_NCRNFishPopEstData %>%
  separate(Id, into = c("project","park","site", "Year", "Species"), sep = "\\_")
NCRNFishPopEstData = separated_dataset %>%
  mutate_if(is.numeric, function(x) round(x, digits = 2))

write.csv(NCRNFishPopEstData,"NCRNFishPopEstData.csv") 





```






















